services:
  postgres:
    image: postgres:18.4-alpine3.24
    container_name: dishes-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dishes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  seq:
    image: datalust/seq:2026.1.17083
    container_name: seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=seqpass
    volumes:
      - seq_data:/data

volumes:
  postgres_data:
  seq_data: