@Api_HostAddress = http://localhost:5056

POST {{Api_HostAddress}}/api/v2/dishes
Content-Type: application/json
Accept: application/json

{
  "name": "Tomato Bread v2",
  "country": "Italy",
  "recipe": "Mix and bake",
  "guid": "ba5e5d58-4bc3-4577-a2fa-adebf912b8f9",
  "ingredients": [
    { "ingredientName": "Tomato", "pricePerUnit": 0.5, "quantity": 2, "guid": "b5f59c6a-dcf9-49e1-9eb7-2de324ddab79" },
    { "ingredientName": "Flour", "pricePerUnit": 1.2, "quantity": 3, "guid": "268c65a2-c30e-44c3-b104-796a64c8939f" }
  ]
}

###
GET {{Api_HostAddress}}/api/v2/dishes
Accept: application/json

###
GET {{Api_HostAddress}}/api/v2/dishes/ba5e5d58-4bc3-4577-a2fa-adebf912b8f9
Accept: application/json



### Deprecated
POST {{Api_HostAddress}}/api/dishes
Content-Type: application/json
Accept: application/json

{
  "name": "Tomato Bread",
  "country": "Italy",
  "recipe": "Mix and bake",
  "ingredients": [
    { "ingredientName": "Tomato", "pricePerUnit": 0.5, "quantity": 2 },
    { "ingredientName": "Flour", "pricePerUnit": 1.2, "quantity": 3 }
  ]
}

###
POST {{Api_HostAddress}}/api/dishes
Content-Type: application/json
Accept: application/json

{
  "name": "Tomato Bread with Paprika",
  "country": "Italy",
  "recipe": "Mix and bake",
  "guid": "a24417b5-1ab1-4322-8ac9-b4bc8b5940b0",
  "ingredients": [
    { "ingredientName": "Tomato", "pricePerUnit": 0.5, "quantity": 2, "guid": "bc172a49-6313-4cbe-8bed-6a51333c7601" },
    { "ingredientName": "Flour", "pricePerUnit": 1.2, "quantity": 3, "guid": "2feac399-21b0-4d40-93c9-c3a60ff5c70c" }
  ]
}

###
GET {{Api_HostAddress}}/api/dishes
Accept: application/json

###
GET {{Api_HostAddress}}/api/dishes/5
Accept: application/json

