@Api_HostAddress = http://localhost:5056

GET {{Api_HostAddress}}/api/dishes
Accept: application/json

###
POST {{Api_HostAddress}}/api/dishes
Content-Type: application/json
Accept: application/json

{
  "name": "Spaghetti Bolognese",
  "country": "Italy",
  "recipe": "Cook pasta, prepare sauce, combine."
}


