@Api_HostAddress = http://localhost:5056

POST {{Api_HostAddress}}/api/v2/dishes
Content-Type: application/json
Accept: application/json

{
  "name": "Tomato Bread v2",
  "country": "Italy",
  "recipe": "Mix and bake",
  "guid": "ba5e5d58-4bc3-4577-a2fa-adebf912b8f9",
  "ingredients": [
    { "ingredientName": "Tomato", "pricePerUnit": 0.5, "quantity": 2, "guid": "b5f59c6a-dcf9-49e1-9eb7-2de324ddab79" },
    { "ingredientName": "Flour", "pricePerUnit": 1.2, "quantity": 3, "guid": "268c65a2-c30e-44c3-b104-796a64c8939f" }
  ]
}

###
GET {{Api_HostAddress}}/api/v2/dishes
Accept: application/json

###
GET {{Api_HostAddress}}/api/v2/dishes/ba5e5d58-4bc3-4577-a2fa-adebf912b8f9
Accept: application/json
